# Generated by Django 5.2.5 on 2025-08-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandinfo',
            name='some_text',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
