# Generated by Django 5.2.5 on 2025-09-07 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="initiator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tours",
                to="booker.band",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="booker.tour",
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zones",
                to="booker.location",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="booker.zone",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="zones",
            field=models.ManyToManyField(related_name="events", to="booker.zone"),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("location", "date"), name="unique_date_and_location"
            ),
        ),
    ]
