# Generated by Django 5.2.5 on 2025-08-21 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='info',
        ),
        migrations.RemoveField(
            model_name='bandinfo',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='bandinfo',
            name='genre',
        ),
        migrations.AddField(
            model_name='band',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bandinfo',
            name='band',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='booker.band'),
            preserve_default=False,
        ),
    ]
