# Generated by Django 5.2.5 on 2025-08-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0002_bandinfo_some_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandinfo',
            name='some_text',
        ),
    ]
