# Generated by Django 5.2.5 on 2025-09-13 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booker", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="band",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="bandinfo",
            options={"ordering": ("band",)},
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ("name", "city")},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("-added_at",)},
        ),
        migrations.AlterModelOptions(
            name="tour",
            options={"ordering": ("title", "initiator")},
        ),
        migrations.AlterModelOptions(
            name="zone",
            options={"ordering": ("location", "name")},
        ),
    ]
