# Generated by Django 5.2.5 on 2025-08-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0002_remove_band_info_remove_bandinfo_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='bands/'),
        ),
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
