# Generated by Django 5.2.5 on 2025-08-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0003_remove_bandinfo_some_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
