# Generated by Django 5.2.5 on 2025-08-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0004_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='rows',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
