# Generated by Django 5.2.5 on 2025-08-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0005_alter_zone_rows_alter_zone_seats'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('location', 'date'), name='unique_date_and_location'),
        ),
    ]
