# Generated by Django 5.2.5 on 2025-08-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0006_event_unique_date_and_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='zones',
            field=models.ManyToManyField(related_name='events', to='booker.zone'),
        ),
    ]
