# Generated by Django 5.2.5 on 2025-08-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0007_event_zones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['location']},
        ),
    ]
