# Generated by Django 5.2.5 on 2025-08-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0008_alter_zone_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['location__name']},
        ),
    ]
