# Generated by Django 5.2.5 on 2025-08-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0009_alter_zone_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={},
        ),
    ]
