# Generated by Django 5.2.5 on 2025-08-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0011_tour_is_active_tour_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='initiator',
            field=models.CharField(default='Sick Solution', max_length=255),
            preserve_default=False,
        ),
    ]
