# Generated by Django 5.2.5 on 2025-08-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0012_tour_initiator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
    ]
