# Generated by Django 5.2.5 on 2025-08-24 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0013_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='booker.band'),
        ),
    ]
