# Generated by Django 5.2.5 on 2025-08-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0014_alter_tour_initiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='avatar',
            field=models.ImageField(default=None, upload_to='bands/'),
            preserve_default=False,
        ),
    ]
