# Generated by Django 5.2.5 on 2025-08-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0015_alter_band_avatar'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket_per_event',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='row',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='has_seats',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='seats',
        ),
    ]
