# Generated by Django 5.2.5 on 2025-08-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0016_remove_ticket_unique_ticket_per_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='invite_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('purchased', 'Purchased'), ('cancelled', 'Cancelled')], default='reserved', max_length=20),
        ),
    ]
