"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@&u&$vaw&0)wqu)4rv)$7#8#xb7q6mrp0*irnm8a1!sf+pj#e='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "booker",
    "debug_toolbar",
    "crispy_forms",
    "crispy_bootstrap5",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "booker.User"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

MEDIA_ROOT = BASE_DIR / "media/"
MEDIA_URL = "media/"

STORAGES = {
    "default": {
        "BACKEND": "base.storage.WindowsCompatibleDropboxStorage",
        "OPTIONS": {
            "oauth2_access_token": "sl.u.AF7jVRhd5b0CJC2BdJLH6h5GVDCULchueDHANVyDDzpNvPPlj-6TxdqVLHljukb2lGNtEHQHwWI44Vu7z2alDO9eVHonjqR_0AWZqzmNFpURnSxJIf4CmqzCfikZor6jFbUCe2DckgdeY7admtxJYJtKWOuEVw8_l6eCSTQ9pdY-PwSK5e59nTe38u4-XWA9dxJfhdPEVMRTI6DOo5ebVpum1LIioijnVyGm7qQyUR7mcpqU8QICK954Bqc5yfmH0S8-ARMWhigy7J7_5QFlEBCaT-fkw77eOu45QUD077AVurkjoBbbn-CBGXeIXm4w0ibSDZI4pEV7cCfiDulPMixwYtEuPHak87QyjALiZqGlnXFD7R8s4AdtVdRutxu-e-1CepobrJxJQjnfCZOiJR3cCd6KY6YYfcfmX96G8mbMGl2q9iKSkdg3JeCr-Je23k7XaxHMC1xDD7FysuFazlHKbf6Kp_1JpCDvv3-nF_z0rACLGepKIq_RJaE7zrZeWDV5HwRJXs0ydQlD02KjgO7xk8XrxpGfmGWOTE58bkaKEPPPSzuSU2-_0A1-yCf18DckGPlTN0VTJD8Ok05bEOiy__eUsyGeYKExUj4IuB8YFXcWm2HbsI41iapEC0D95W4eiQ2h5sm1VZmMniru5cgQSJtqut27paxtWMloKuq0RjHwCRD27-BpZ_sQBYN4rY6toVqRSB63TciR4nQLIkgK1dpLqYJIJw3gEx3HiUT27_30WvHnmeNJUH558CxCGHsR2pj3s2xeFXd6vxt6t_iSPFzw2OUiRlmCxqo8i4X5iGkd6uuVS18XxD6QJmUEZqfgQ0pQu8VqgtHwrPAIX9zFdY7xczfh95pibPmuvfaaFjjw06JyV_iUAvkZVGKfXoSkNgMC5tQcCjKvI86YumwxMvZRdmSGgSHAWr1OcNFR_01jpUm9yeBQ00-J3b8DrkIo2WY4a4lCf4BDTubt5NwEW0OYZ6Y8x1505FAyJPTqYn-ru5zABGkpsUKcX2EDn40DDbVIntByr_rE7W2Q2gvKmOJTonXDrGcS4gpVGJHBApi3h75yO9FBJ-01P0bag4meDk9Xzk0cWVoRFc-_BM8I3fv3c8jF3SAN0i095ODkmSTbfxEmBwullHzXXj4GOlwQYqtALlNU7RXJRe04-kqT3jWanfBUniCPiK_hxvuoS285hQRqby47KhTROorK5uCDil95ajhrFizpgWsEcLc-nd5n0re-mxHn574-N5TNIqK9fMLcPoSqFKa66ZxNDvxQwRJj2Mz0Yodr-EOD1g5H",
            "oauth2_refresh_token": "8crpD6EaOTAAAAAAAAAAAYDjYP7SkQUU0dNnlx8RwomlERk7aALtIDjSUWlkOdn8",
            "app_secret": "l3akayj6upsdluv",
            "app_key": "b574bh4wl14m7ck",
            "root_path": "media/",
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

INTERNAL_IPS = [
    "127.0.0.1",
]

# Emailing settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_FROM = 'vovaafon25@gmail.com'
EMAIL_HOST_USER = 'vovaafon25@gmail.com'
EMAIL_HOST_PASSWORD = 'wcqkyujkkblqzdki'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

PASSWORD_RESET_TIMEOUT = 14400

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"
